package eu.kartoffelquadrat.lobbyservice.samplegame.controller;

/**
 * Generic Action interface for blackboard architecture. Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 *
 * @Author: Maximilian Schiedermeier
 * @Date: December 2020
 */
public interface Action {
}
